
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: 'Uso de versión 3.10'

- script: |
    python -m pip install --upgrade pip
    pip install requests
  displayName: 'Instalar dependencias necesarias'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo ${env:ID}'

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      import requests
      import os
      
      def call_api():
          url = "https://api-colombia.com/api/v1/Department"
          id = os.environ["ID"]
          try:
              response = requests.get(url)
              response.raise_for_status()
      
              data = response.json()
              print(id)
              print('Información de los departamentos de Colombia: \n {}'.format(data))
              
          except requests.exceptions.RequestException as e:
              print("Error al llamar a la API:", e)
      
      call_api()
  displayName: 'Prueba ejecución de Script en el mismo pipeline'